services:
  nginx:
    image: nginx:latest
    ports:
      - 80:80
    env_file:
      - .env
    volumes:
      - ./nginx:/etc/nginx/templates
    networks:
      towerdefensenet:
        aliases:
          - graph.towerdefense.test
          - towerdefense.test

  db:
    image: mongo:6
    hostname: db
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_ROOT_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_ROOT_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGO_DATABASE}
      MONGO_USER: ${MONGO_USER}
      MONGO_PASSWORD: ${MONGO_PASSWORD}
    volumes:
      - ./data/db:/data/db
      - ./scripts/database/:/docker-entrypoint-initdb.d/
    networks:
      - towerdefensenet

  gateway:
    image: node:20
    hostname: gateway
    working_dir: /app
    volumes:
      - ./server:/app
    env_file:
      - .env
    depends_on:
      - microservice-players
      - microservice-games
    networks:
      - towerdefensenet
    command: sh -c "exec yarn start:dev gateway"

  microservice-auth:
    image: node:20
    hostname: microservice-auth
    working_dir: /app
    volumes:
      - ./server:/app
    env_file:
      - .env
    depends_on:
      - db
    networks:
      - towerdefensenet
    command: sh -c "exec yarn start:dev microservice-auth"

  microservice-players:
    image: node:20
    hostname: microservice-players
    working_dir: /app
    volumes:
      - ./server:/app
    env_file:
      - .env
    depends_on:
      - db
    networks:
      - towerdefensenet
    command: sh -c "exec yarn start:dev microservice-players"

  microservice-games:
    image: node:20
    hostname: microservice-games
    working_dir: /app
    volumes:
      - ./server:/app
    env_file:
      - .env
    depends_on:
      - db
    networks:
      - towerdefensenet
    command: sh -c "exec yarn start:dev microservice-games"

  client:
    image: node:20
    hostname: client
    working_dir: /app
    volumes:
      - ./client:/app
    env_file:
      - .env
    ports:
      - 3000:3000
      - 24678:24678
    networks:
      - towerdefensenet
    command: sh -c "rm -rf /tmp/nitro/worker-* && exec yarn dev --host=0.0.0.0"

networks:
  towerdefensenet:
    driver: bridge